packages:
  - 'packages/*'
  - 'packages/ports/*'
ignoreWorkspaceRootCheck: true
minimumReleaseAge: 3
strictPeerDependencies: false
autoInstallPeers: true
allowBuilds:
  '@google/genai': false
  '@swc/core': true
  esbuild: true
  nx: true
  protobufjs: false
