import rawPorts from '../data/ports.json';
import type { PortInfo } from './types';

// ports.json is generated by tools/scripts/ports-manifest.mjs from each port's
// package.json, so it's trusted local data — no runtime validation needed.
export const portList = rawPorts as PortInfo[];
